#ifndef PATODATAMODEL_GLOBAL_H
#define PATODATAMODEL_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PATODATAMODEL_LIBRARY)
#  define PATODATAMODELSHARED_EXPORT Q_DECL_EXPORT
#else
#  define PATODATAMODELSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // PATODATAMODEL_GLOBAL_H
