#ifndef PATOCOMMUNICATION_GLOBAL_H
#define PATOCOMMUNICATION_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PATOCOMMUNICATION_LIBRARY)
#  define PATOCOMMUNICATIONSHARED_EXPORT Q_DECL_EXPORT
#else
#  define PATOCOMMUNICATIONSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // PATOCOMMUNICATION_GLOBAL_H
