#ifndef PATOSERVERAPI_GLOBAL_H
#define PATOSERVERAPI_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PATOSERVERAPI_LIBRARY)
#  define PATOSERVERAPISHARED_EXPORT Q_DECL_EXPORT
#else
#  define PATOSERVERAPISHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // PATOSERVERAPI_GLOBAL_H
